### ISSUE TITLE
isolate macro constants

### ISSUE THREAD

**Issue by jmvdwerf** [fuegas/arm-loconet-starter#13]
To ease the use of different constant values over the projects, I think it is wise to isolate these constants in their own #ifndef environments.

E.g. for the number of CV values:

    #ifndef LOCONET_CV_NUMBERS
      #define LOCONET_CV_NUMBERS          0x1E  // 30
    #endif

By the way, for the ringbuffer size in loconet_rx.c, we already did this:
```
//-----------------------------------------------------------------------------
// Define LOCONET_RX_RINGBUFFER_Size if it's not defined
#ifndef LOCONET_RX_RINGBUFFER_Size
#define LOCONET_RX_RINGBUFFER_Size 64
#endif
```
But it's in the .c file, and not in the .h file...

**Comment by fuegas** [comment]
Agree on the need for it. It was not done in `loconet_rx.c` because it is only used for the buffer created, it does not need to be exposed to external components.

**Comment by jmvdwerf** [comment]
Fine by me. Just to be sure :)
