### ISSUE TITLE
Add unit-tests and framework

### ISSUE THREAD

**Issue by jmvdwerf** [fuegas/arm-loconet-starter#20]
Set up a framework to be able to do unit tests on the code. Especially when developing our own applications on top of the loconet framework, it would be great if we could add unit tests. E.g. to test whether the system responds correctly on receiving a message, or responds well on the fast clock...

My suggestion would be to use unity: http://www.throwtheswitch.org/unity/

**Comment by fuegas** [comment]
We tried, alas, it didn't work due to differences in architectures on which the code and tests have to be built.
